#Defining two services
#API container
#MongoDB container
services:

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/notesdb

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"